<?php

return [
    'modules' => [
        'tarifas-servicio' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Gerente'       => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show'],
            'Cliente'       => [],
            'Empresa'       => [],
        ],
        'empresas' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Gerente'       => ['index','show','update'],
            'Técnico'       => ['index','show'],
            'Cliente'       => [],
            'Empresa'       => [],
        ],
        'usuarios' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Gerente'       => ['index','show','update'],
            'Técnico'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'autenticacion-usuarios' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Gerente'       => ['index','show'],
            'Técnico'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'equipos' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store','update'],
            'Gerente'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'propiedad-equipos' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store','update'],
            'Gerente'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'servicios' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store','update','destroy','partes.index','partes.store','partes.update','partes.destroy'],
            'Gerente'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'garantias' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store','update'],
            'Gerente'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
        'repuestos' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show'],
            'Gerente'       => ['index','show'],
            'Cliente'       => [],
            'Empresa'       => [],
        ],
        'inventario' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store'],
            'Gerente'       => ['index','show'],
            'Cliente'       => [],
            'Empresa'       => [],
        ],
        'solicitud-repuestos' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show','store','update'],
            'Gerente'       => ['index','show','update'],
            'Cliente'       => ['index','show','store'],
            'Empresa'       => [],
        ],
        'notificaciones' => [
            'Administrador' => ['index','show','store','update','destroy','setLeida','markAllAsRead'],
            'Técnico'       => ['index','show','store','setLeida','markAllAsRead'],
            'Gerente'       => ['index','show','setLeida','markAllAsRead'],
            'Cliente'       => ['index','show','setLeida','markAllAsRead'],
            'Empresa'       => [],
        ],
        'reportes' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Gerente'       => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show'],
            'Cliente'       => [],
            'Empresa'       => [],
        ],
        'rma' => [
            'Administrador' => ['index','show','store','update','destroy'],
            'Técnico'       => ['index','show'],
            'Gerente'       => ['index','show'],
            'Cliente'       => ['index','show'],
            'Empresa'       => [],
        ],
    ],

    // Rutas personalizadas (no apiResource)
    'routes' => [
        'dashboard.index' => ['Administrador','Técnico','Gerente','Cliente'],
        'rbac.me' => ['Administrador','Técnico','Gerente','Cliente','Empresa'],
        'stats.show' => ['Administrador','Técnico','Gerente','Cliente'],
        'stats.batch' => ['Administrador','Técnico','Gerente','Cliente'],
        'permissions.index' => ['Administrador','Gerente'],
        'permissions.update' => ['Administrador','Gerente'],
        'permissions.reset' => ['Administrador','Gerente'],
        'maintenance.backfill' => ['Administrador','Gerente'],
        'usuarios.notifications.get' => ['Administrador','Técnico','Gerente','Cliente'],
        'usuarios.notifications.set' => ['Administrador','Técnico','Gerente'],
        'servicios.partes.index'     => ['Administrador','Técnico','Gerente'],
        'servicios.partes.store'     => ['Administrador','Técnico'],
        'servicios.partes.update'    => ['Administrador','Técnico','Gerente'],
        'servicios.partes.destroy'   => ['Administrador','Técnico','Gerente'],
        'tarifas-servicio.historial.index' => ['Administrador','Gerente','Técnico'],
    ],
];
